default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { "postgres://postgres:postgres@localhost:5432/fullstack_take_home_development" } %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { "postgres://postgres:postgres@localhost:5432/fullstack_take_home_test" } %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
